version: '3'
services:
  
  app:
    image: openjdk:15
    container_name: app
    ports:
      - 8090:8080
    tty: true
    volumes:
      - . :/srv:cached
    working_dir: /srv
    depends_on:
      - db

  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.8
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  database:


